spring.application.name=employee
spring.security.user.name=${POSTGRES_APP_USERNAME}
spring.security.user.password=${POSTGRES_APP_PASSWORD}
################################  Postgres  #########################
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=
#spring.datasource.password=
#spring.datasource.driver-class-name=org.postgresql.Driver # Spring Boot can infer this from the URL
################################  Hibernate  #########################
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET}
################################  Email  #########################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=${GEMAI_APP_USERNAME}
#spring.mail.password=${GEMAI_APP_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
################################  Variable  #########################
backend.origin=http://localhost:8080
################################  flyway  #########################
spring.flyway.enabled=true
################################  Observability  #########################
management.endpoints.web.exposure.include=health,prometheus,metrics